// J1939 SPN/FMI Fault Code Database
// Comprehensive offline lookup for truck engine diagnostics
// Covers Cummins, generic J1939, aftertreatment, transmission, ABS, electrical

const J1939_DB = {

  // ─── FMI Codes (Failure Mode Identifiers) ── All 32 standard J1939 FMIs ───
  fmi: {
    0:  "Data Valid But Above Normal Operational Range - Most Severe Level",
    1:  "Data Valid But Below Normal Operational Range - Most Severe Level",
    2:  "Data Erratic, Intermittent, or Incorrect",
    3:  "Voltage Above Normal, or Shorted to High Source",
    4:  "Voltage Below Normal, or Shorted to Low Source",
    5:  "Current Below Normal or Open Circuit",
    6:  "Current Above Normal or Grounded Circuit",
    7:  "Mechanical System Not Responding or Out of Adjustment",
    8:  "Abnormal Frequency or Pulse Width or Period",
    9:  "Abnormal Update Rate",
    10: "Abnormal Rate of Change",
    11: "Root Cause Not Known",
    12: "Bad Intelligent Device or Component",
    13: "Out of Calibration",
    14: "Special Instructions",
    15: "Data Valid But Above Normal Operating Range - Least Severe Level",
    16: "Data Valid But Above Normal Operating Range - Moderately Severe Level",
    17: "Data Valid But Below Normal Operating Range - Least Severe Level",
    18: "Data Valid But Below Normal Operating Range - Moderately Severe Level",
    19: "Received Network Data in Error",
    20: "Data Drifted High",
    21: "Data Drifted Low",
    22: "Reserved for Future Use",
    23: "Reserved for Future Use",
    24: "Reserved for Future Use",
    25: "Reserved for Future Use",
    26: "Reserved for Future Use",
    27: "Reserved for Future Use",
    28: "Reserved for Future Use",
    29: "Reserved for Future Use",
    30: "Reserved for Future Use",
    31: "Condition Exists"
  },

  // ─── SPN Codes (Suspect Parameter Numbers) ────────────────────────────────
  spn: {
    // ── Engine Core Parameters ──
    27:   "EGR Valve Position",
    28:   "EGR Valve Position Command",
    29:   "EGR Valve Controller",
    51:   "Throttle Position",
    70:   "Parking Brake Switch",
    74:   "Maximum Road Speed Limit",
    84:   "Vehicle Speed (Wheel-Based)",
    91:   "Accelerator Pedal Position",
    92:   "Engine Percent Load at Current Speed",
    94:   "Fuel Delivery Pressure",
    96:   "Fuel Level",
    97:   "Water in Fuel Indicator",
    98:   "Engine Oil Level",
    100:  "Engine Oil Pressure",
    101:  "Crankcase Pressure",
    102:  "Turbocharger Boost Pressure",
    103:  "Turbocharger Speed",
    105:  "Intake Manifold Temperature",
    106:  "Air Inlet Pressure",
    107:  "Air Filter Differential Pressure",
    108:  "Barometric Pressure",
    110:  "Engine Coolant Temperature",
    111:  "Engine Coolant Level",
    112:  "Coolant Filter Differential Pressure",
    113:  "Governor Droop",
    114:  "Net Battery Current",
    115:  "Alternator Current",
    120:  "Hydraulic Oil Pressure",
    121:  "Engine Retarder Switches",
    122:  "Engine Retarder Percent Torque",
    123:  "Clutch Pressure",
    124:  "Transmission Oil Level",
    126:  "Transmission Oil Pressure",
    127:  "Transmission Oil Temperature",
    132:  "Mass Air Flow",
    154:  "Intake Manifold 2 Temperature",
    155:  "Intake Manifold 2 Pressure",
    156:  "Injector Timing Rail Pressure",
    157:  "Injector Metering Rail Fuel Pressure",
    158:  "Battery Potential (Voltage) - Switched",
    162:  "Transmission Torque Converter Ratio",
    163:  "Transmission Current Gear",
    164:  "Injection Control Pressure",
    166:  "Engine Rated Power",
    167:  "Alternator Potential (Voltage)",
    168:  "Battery Potential / Power Input",
    171:  "Ambient Air Temperature",
    172:  "Intake Manifold Air Temperature",
    173:  "Exhaust Gas Temperature",
    174:  "Fuel Temperature",
    175:  "Engine Oil Temperature",
    176:  "Turbo Oil Temperature",
    177:  "Transmission Oil Temperature (High Range)",
    183:  "Engine Fuel Rate",
    184:  "Instantaneous Estimated Brake Power",
    188:  "Engine Speed at Idle, Point 1",
    189:  "Engine Speed at High Idle",
    190:  "Engine Speed (RPM)",
    228:  "Speed Sensor Calibration",
    229:  "Cruise Control Set Speed",
    230:  "Power Specific Fuel Consumption",
    231:  "Trip Average Fuel Economy",
    232:  "Total Fuel Used",
    233:  "Refrigerant Low Pressure Switch",
    234:  "AC High Pressure Fan Switch",
    235:  "Total Idle Hours",
    236:  "Total Idle Fuel Used",
    237:  "Vehicle Identification Number",
    238:  "Engine Make",
    239:  "Engine Model",
    240:  "Engine Serial Number",
    241:  "Engine Unit Number",
    242:  "Software Identification",
    243:  "Engine ECU Build Number",
    244:  "Trip Distance",
    245:  "Total Vehicle Distance",
    246:  "Trip Vehicle Distance",
    247:  "Total Engine Hours",
    248:  "Total PTO Hours",
    249:  "Total Engine Revolutions",
    250:  "Total Vehicle Hours",

    // ── Driver/Torque Parameters ──
    512:  "Driver Demand Engine Percent Torque",
    513:  "Actual Engine Percent Torque",
    514:  "Nominal Friction Percent Torque",
    515:  "Engine Desired Operating Speed",
    516:  "Engine Desired Operating Speed Asymmetry Adjustment",
    518:  "Engine Requested Torque",
    519:  "Engine Demand Percent Torque",
    520:  "Post-Trip Idle Fuel Consumption",
    521:  "Trip Fuel Consumption",
    522:  "Trip Distance",
    523:  "Trip Time - Engine Running",
    524:  "Trip Time - Engine Idle",
    526:  "Trip Time - Engine PTO Active",
    527:  "Trip Time - Engine Cruise Active",

    // ── EGR / Emissions ──
    411:  "EGR Valve Control Circuit",
    412:  "EGR Temperature",
    544:  "Engine Coolant Diversion Valve",
    558:  "Accelerator Pedal Position Low Idle Switch",
    559:  "Accelerator Pedal Position Kickdown Switch",
    563:  "EGR Mass Flow Rate",
    595:  "Cruise Control Active",
    596:  "Cruise Control Enable Switch",
    597:  "Brake Switch",
    598:  "Clutch Switch",

    // ── Aftertreatment / DPF / DEF / SCR ──
    1127: "Turbocharger Compressor Inlet Pressure",
    1172: "Turbocharger Oil Temperature",
    1173: "Turbocharger Speed (2)",
    1176: "DPF Differential Pressure",
    1180: "Aftertreatment Exhaust Gas Temperature 1 (DPF Inlet)",
    1181: "Aftertreatment Exhaust Gas Temperature 2 (DPF Outlet)",
    1232: "Fan Drive State",
    1233: "Engine Desired Fan Speed",
    1235: "Engine Coolant Pump Differential Pressure",
    1237: "Engine Exhaust Back Pressure",
    1239: "Engine Fuel Pump Suction Pressure",
    1321: "Aftertreatment SCR Catalyst Inlet Temperature",
    1322: "Aftertreatment SCR Catalyst Outlet Temperature",
    1323: "Aftertreatment SCR Catalyst Inlet Pressure",
    1324: "Aftertreatment SCR Catalyst Outlet Pressure",

    1569: "Engine Protection System Configuration",
    1568: "Engine Torque Mode",
    1571: "Engine Protection System Timer State",
    1572: "Engine Protection System Timer Override",
    1590: "Engine Coolant Pump Speed",
    1600: "Cold Start Emission Reduction Strategy",
    1624: "Actual Maximum Available Engine Torque",
    1636: "Intake Valve Actuation System Oil Pressure",
    1637: "Intake Valve Actuation System Oil Temperature",
    1638: "Aftertreatment 1 Fuel Pressure",
    1639: "Aftertreatment 1 Fuel Rate",

    1675: "Engine Starter Mode",
    1692: "Engine Turbocharger Compressor Inlet Temperature",

    1761: "Aftertreatment DEF Tank Level",
    1762: "Aftertreatment DEF Tank Temperature",
    1763: "Aftertreatment DEF Concentration",

    1855: "Engine Crankcase Breather Oil Separator Speed",
    1856: "Engine Timing Actuator Position",

    2000: "SAE J1939 Axle Group",
    2003: "Aftertreatment SCR Catalyst Reagent (DEF) Line Heater",
    2012: "Aftertreatment Fuel Pressure 2",

    // ── Transmission / Drivetrain ──
    2814: "Transmission Requested Gear",
    2815: "Transmission Current Gear (2)",
    2816: "Transmission Actual Gear Ratio",
    2817: "Transmission Selected Gear",
    2818: "Transmission Shift In Progress",
    2819: "Transmission Torque Converter Lockup Engaged",
    2820: "Transmission Driveline Engaged",
    2879: "Transmission Shift Inhibit Indicator",

    2791: "Engine Exhaust Gas Recirculation (EGR) Valve Control",
    2795: "Engine Variable Geometry Turbocharger (VGT) Actuator",

    // ── Aftertreatment Continued ──
    3031: "Aftertreatment SCR Intake NOx Sensor",
    3032: "Aftertreatment SCR Intake NOx Sensor Preliminary",
    3033: "Aftertreatment SCR Intake NOx Sensor Heater Control",
    3034: "Aftertreatment SCR Intake NOx Sensor Heater Status",
    3050: "Aftertreatment DEF Pump Motor Speed",
    3058: "Aftertreatment SCR Outlet NOx Sensor",
    3216: "Aftertreatment DPF Intake Pressure",
    3217: "Aftertreatment DPF Outlet Pressure",
    3226: "Aftertreatment SCR Catalyst Conversion Efficiency",
    3230: "Aftertreatment DPF Ash Load Percent",
    3236: "Aftertreatment DPF Average Time Between Regenerations",
    3242: "Aftertreatment DPF Soot Load Percent",
    3245: "Aftertreatment DPF Time Since Last Regeneration",
    3246: "Aftertreatment DPF Regeneration Inhibit Switch",
    3249: "Aftertreatment DPF Regeneration Force Switch",
    3250: "Aftertreatment DPF Status",
    3251: "Aftertreatment DPF Regeneration Status",

    3361: "SCR Operator Inducement System",
    3362: "SCR Operator Inducement Severity",
    3363: "SCR Catalyst System Status",
    3364: "SCR System Monitor",

    3464: "Engine Exhaust Gas Recirculation Cooler Efficiency",
    3471: "Aftertreatment DEF Pump Pressure",
    3475: "Engine EGR Cooler Delta Pressure",
    3476: "Aftertreatment DEF Tank Heater",
    3479: "Aftertreatment DPF High Exhaust Temperature Lamp Command",
    3480: "Aftertreatment SCR Operator Inducement Active",
    3482: "Aftertreatment DEF Dosing Unit Actual Dosing Quantity",
    3490: "Aftertreatment DEF Dosing Line",
    3491: "Aftertreatment DEF Dosing Unit Input Line",
    3492: "Aftertreatment DEF Dosing Unit Return Line",
    3505: "Aftertreatment DPF Regeneration Type",
    3510: "Aftertreatment DEF Quality",
    3515: "Aftertreatment DEF Pump Motor",
    3516: "Aftertreatment SCR Catalyst Bed Temperature",
    3521: "Aftertreatment DEF Absolute Pressure",
    3524: "Aftertreatment DPF Outlet Temperature (2)",
    3540: "Aftertreatment DPF Soot Load Regeneration Threshold",
    3556: "Aftertreatment DEF Supply Pressure",
    3563: "Engine Particulate Matter (PM) Filter System",
    3582: "Aftertreatment DPF Regeneration Duration",
    3597: "Engine System Diagnostic Link",
    3609: "Aftertreatment SCR NOx Catalyst System Overall Status",
    3610: "Aftertreatment SCR Inducement Fault Timer",

    3700: "Aftertreatment SCR Outlet NOx Monitor",
    3713: "Aftertreatment DEF Dosing System",
    3719: "Aftertreatment SCR Operator Inducement Lamp Data",
    3720: "Aftertreatment DPF Incomplete Regeneration",

    // ── ABS / Brakes ──
    561:  "ABS - Wheel Speed Sensor Circuit (Drive Axle, Left)",
    562:  "ABS - Wheel Speed Sensor Circuit (Drive Axle, Right)",
    563:  "EGR Mass Flow Rate",
    575:  "ABS - Electronic Control Unit (ECU)",
    576:  "ABS - Wheel Speed Sensor Circuit (Steer Axle, Left)",
    577:  "ABS - Wheel Speed Sensor Circuit (Steer Axle, Right)",
    579:  "ABS - Traction Control",
    611:  "ABS - Wheel Speed Sensor Circuit (Trailer)",
    612:  "ABS - Modulator Valve (Drive Axle, Left)",
    613:  "ABS - Modulator Valve (Drive Axle, Right)",
    614:  "ABS - Modulator Valve (Steer Axle, Left)",
    615:  "ABS - Modulator Valve (Steer Axle, Right)",
    616:  "ABS - Warning Lamp",
    617:  "ABS - Retarder Relay Valve",
    618:  "ABS - Relay Diagonal 1",
    619:  "ABS - Relay Diagonal 2",
    625:  "CAN Bus Communication Link",
    627:  "Power Supply Voltage (ECU Internal)",
    628:  "Power Supply (ECU Internal - Keep Alive Memory)",
    629:  "Controller #1",
    630:  "Calibration Memory",

    // ── Electrical / Communication ──
    631:  "Controller #2 (ECU)",
    632:  "Controller RAM Failure",
    633:  "Controller ROM Failure",
    634:  "Controller EEPROM Failure",
    636:  "Engine ECU Processor",
    637:  "Engine ECU Critical Internal Failure",
    638:  "Engine ECU Hardware",
    639:  "J1939 Data Link",
    640:  "ECU Operating Voltage",
    641:  "VGT Actuator Driver Circuit",
    651:  "Injector Cylinder #1",
    652:  "Injector Cylinder #2",
    653:  "Injector Cylinder #3",
    654:  "Injector Cylinder #4",
    655:  "Injector Cylinder #5",
    656:  "Injector Cylinder #6",
    657:  "Injector Cylinder #7",
    658:  "Injector Cylinder #8",

    // ── Misc Engine / Exhaust ──
    677:  "Starter Solenoid Valve",
    678:  "Engine Shutdown Override Switch",
    679:  "Engine Shutdown Timer Status",
    702:  "Auxiliary Input/Output #1",
    703:  "Auxiliary Input/Output #2",
    704:  "Auxiliary Input/Output #3",
    705:  "Auxiliary Input/Output #4",
    706:  "Auxiliary Input/Output #5",
    723:  "Engine Crankshaft / Camshaft Timing Misalignment",
    729:  "Intake Air Heater Relay",
    730:  "Air Shutoff Valve",
    731:  "Auxiliary Output #6",
    971:  "Idle Shutdown Timer - Driver Alert Mode",
    972:  "Idle Shutdown Timer - Shutdown Imminent",
    973:  "Idle Shutdown Timer - Engine Override Active",
    974:  "Remote Accelerator Pedal Position",
    976:  "PTO Governor State",

    1072: "Engine Brake Actuator",
    1073: "Engine Brake Solenoid",
    1074: "Engine Brake Enable Switch",
    1075: "Engine Brake Low Medium High Switch",
    1076: "Engine Brake System Feedback",
    1077: "Engine Brake Solenoid (2)",
    1078: "Engine Brake Solenoid (3)",
    1079: "Engine Brake Actuator (Low)",
    1080: "Engine Brake Actuator (Medium)",
    1081: "Engine Brake Actuator (High)",

    1109: "Engine Protection System Warning Indicator",
    1110: "Engine Protection System Shutdown Indicator",

    1209: "Exhaust Back Pressure Regulator Position",
    1210: "Exhaust Back Pressure Regulator Command",

    // ── Additional Critical SPNs ──
    3826: "Aftertreatment SCR Catalyst Tank Low Level Indicator",
    3981: "Aftertreatment NOx Sensor Module",
    4094: "Engine Protection Torque Derate",
    4096: "Aftertreatment SCR Catalyst System Fault",
    4334: "Aftertreatment Outlet NOx Sensor",
    4354: "Aftertreatment DPF High Temperature Abort",
    4356: "Aftertreatment DPF Regeneration Needed Warning",
    4360: "Aftertreatment DEF Dosing Absolute Pressure",
    4364: "Aftertreatment DEF Quality Event",
    4375: "Aftertreatment SCR System Fault (Derate)",

    4677: "Aftertreatment DPF Regeneration Frequency",
    4752: "Aftertreatment DEF Header",
    4766: "Aftertreatment DEF Dosing Valve",
    4768: "Aftertreatment DEF Pump",
    4792: "Aftertreatment DEF Control Module",

    4795: "Aftertreatment Hydrocarbon Doser",
    5018: "Engine Cylinder Misfire",
    5019: "Engine Cylinder Misfire at Idle",

    5246: "Aftertreatment Exhaust Gas Temperature Sensor",
    5297: "Aftertreatment DPF System Performance",
    5357: "Aftertreatment SCR System Performance",
    5397: "Engine System Diagnostic Trouble Code",
    5444: "Aftertreatment DEF Pump Pressure Relief Valve",
    5454: "Aftertreatment DPF Regeneration System",
    5466: "Aftertreatment SCR Operator Inducement Override",
    5571: "Aftertreatment DEF Doser Coolant Valve",
    5742: "Measured Fuel Rail Pressure",
    5743: "Desired Fuel Rail Pressure",
    5837: "Fuel System Control",
    5853: "Aftertreatment DEF Return Line",

    5964: "Aftertreatment NOx Sensor Power Supply",
    6033: "Aftertreatment DEF Dosing Metering Unit",
    6254: "Aftertreatment DEF Tank Sensor",
    6393: "Engine Fuel System Leak Detected",
    6595: "Aftertreatment NOx Sensor Self-Diagnostic",
    6634: "Aftertreatment DPF Over Temperature Protection",
    6713: "Aftertreatment DPF Uncontrolled Regeneration",
    6802: "Engine Fuel Filter Restriction",
    6918: "Engine Control Module Tamper Protection",
    6966: "Aftertreatment DEF Tank Apparent Level",
    7100: "Aftertreatment SCR Conversion Catalyst Deterioration",
    7333: "Engine Crank Inhibit Device",
    7602: "Aftertreatment Fuel Injector Control"
  },

  // ─── Lookup Function ──────────────────────────────────────────────────────
  lookup: function(spn, fmi) {
    var spnNum = parseInt(spn, 10);
    var fmiNum = parseInt(fmi, 10);
    var spnDesc = this.spn[spnNum] || "Unknown SPN " + spnNum;
    var fmiDesc = this.fmi[fmiNum] || "Unknown FMI " + fmiNum;
    var fullDesc = "SPN " + spnNum + " - " + spnDesc + " / FMI " + fmiNum + " - " + fmiDesc;
    return {
      spn: spnNum,
      fmi: fmiNum,
      spnDesc: spnDesc,
      fmiDesc: fmiDesc,
      fullDesc: fullDesc
    };
  }
};
